Ureca-Dangdang-salon/dang_server

src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java, src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java, src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequestProfiles.java, src/main/java/com/dangdangsalon/domain/groomerprofile/review/entity/Review.java, src/main/java/com/dangdangsalon/domain/groomerprofile/review/entity/ReviewImage.java, src/main/resources/db/migration/V2__Add_review_Image.sql, src/main/resources/db/migration/V3__Add_estimate_request.sql
> #4 
> 피그마에 맞게 ERD 수정 (리뷰, 리뷰 이미지, 견적서, 견적서 양식 ..)
>
=> Refactor: 엔티티 수정

src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerCertification.java, src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerDetails.java, src/main/resources/db/migration/V4__Add_groomer_request.sql
> #4 
> 미용사 자격증 엔티티 추가 및 Flyway V4 적용
>
=> Refactor: 미용사 자격증 엔티티 추가 및 Flyway V4 적용

build.gradle, src/main/java/com/dangdangsalon/config/SecurityConfig.java, src/main/java/com/dangdangsalon/config/WebConfig.java
=> Feat: CORS 설정을 위한 Config 클래스 생성

src/main/java/com/dangdangsalon/domain/dogprofile/controller/DogProfileController.java, src/main/java/com/dangdangsalon/domain/dogprofile/dto/DogProfileResponseDto.java, src/main/java/com/dangdangsalon/domain/dogprofile/repository/DogProfileFeatureRepository.java, src/main/java/com/dangdangsalon/domain/dogprofile/repository/DogProfileRepository.java, src/main/java/com/dangdangsalon/domain/dogprofile/service/DogProfileService.java, src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/DogEstimateRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/DogRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateDetailResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/FeatureResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/ServiceResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestProfilesRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailService.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertService.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java, src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerCanServiceRepository.java, src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerServiceAreaRepository.java, src/main/java/com/dangdangsalon/domain/groomerprofile/request/entity/GroomerEstimateRequest.java, src/main/java/com/dangdangsalon/domain/groomerprofile/request/repository/GroomerEstimateRequestRepository.java, src/main/java/com/dangdangsalon/domain/groomerservice/repository/GroomerServiceRepository.java, src/main/java/com/dangdangsalon/domain/region/repository/DistrictRepository.java, src/main/java/com/dangdangsalon/domain/user/repository/UserRepository.java, src/main/resources/db/migration/V4__Add_groomer_request.sql
> #11 
> 견적서 요청시 반려견 조회 기능 구현
> 견적서 요청 등록 기능 구현 (같은 지역과 미용사가 회원 가입시 선택한 서비스 안에 견적 요청시 선택한 서비스가 다 포함되어야하고 서비스 타입이 맞아야 해당 미용사한테 견적 요청이 간다)
> 견적서 요청 조회(미용사) 기능 구현
> 견적서 요청 상세 조회(미용사) 기능 구현 
> 견적서 요청 삭제(미용사) 기능 구현
> 견적서 요청시 반려견 조회
> 견적서 요청 등록 기능
> 견적서 요청 조회(미용사) 
> 견적서 요청 상세 조회(미용사) 
>
> 초반 코드 리뷰 많은 조언 받겠습니다!!
=> Feature: 견적 요청 등록, 반려견 조회 기능 구현

src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java, src/main/java/com/dangdangsalon/domain/estimate/dto/MyEstimateDetailResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/dto/MyEstimateResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/DogNameResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/MyEstimateRequestDetailResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/MyEstimateRequestResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestProfilesRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailService.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertService.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
> #28
> 내 견적서 요청 조회(채팅)
> 내 견적서 요청 상세 조회(채팅)
> 내 견적서 조회(카드 형식) <- 일단은 총 금액만 가져옴
> 내 견적서 상세 조회
> 견적서 그만 받기
>
=> Feat: 사용자 입장 견적서 API

.gitignore, build.gradle, src/main/java/com/dangdangsalon/domain/contest/entity/ContestPost.java, src/main/java/com/dangdangsalon/domain/contest/repository/ContestPostRepository.java, src/main/java/com/dangdangsalon/domain/contest/service/ContestPostLikeService.java, src/main/java/com/dangdangsalon/domain/contest/service/ContestService.java, src/main/java/com/dangdangsalon/domain/user/entity/User.java, src/main/resources/db/migration/V1__initial_schema.sql, src/main/resources/db/migration/V2__Add_review_Image.sql, src/main/resources/db/migration/V3__Add_estimate_request.sql, src/main/resources/db/migration/V4__Add_groomer_request.sql, src/main/resources/db/migration/V5__add_post_like.sql, src/test/java/com/dangdangsalon/domain/auth/controller/AuthControllerTest.java, src/test/java/com/dangdangsalon/domain/contest/api/ContestApiTest.java, src/test/java/com/dangdangsalon/domain/contest/controller/ContestControllerTest.java, src/test/java/com/dangdangsalon/domain/contest/controller/ContestPostControllerTest.java, src/test/java/com/dangdangsalon/domain/contest/repository/ContestPostLikeRepositoryTest.java, src/test/java/com/dangdangsalon/domain/contest/repository/ContestPostRepositoryTest.java, src/test/java/com/dangdangsalon/domain/contest/repository/ContestRepositoryTest.java, src/test/java/com/dangdangsalon/domain/contest/service/ContestPostLikeServiceTest.java, src/test/java/com/dangdangsalon/domain/contest/service/ContestPostServiceTest.java, src/test/java/com/dangdangsalon/domain/contest/service/ContestServiceTest.java, src/test/resources/application-test.properties
> ex) #29 
> 콘테스트 API 테스트 코드 작성
>
=> Test: 콘테스트 API 테스트 코드 작성

build.gradle, src/main/java/com/dangdangsalon/config/WebClientConfig.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java, src/main/java/com/dangdangsalon/domain/orders/controller/OrdersController.java, src/main/java/com/dangdangsalon/domain/orders/dto/OrdersRequestDto.java, src/main/java/com/dangdangsalon/domain/orders/dto/OrdersResponseDto.java, src/main/java/com/dangdangsalon/domain/orders/entity/OrderStatus.java, src/main/java/com/dangdangsalon/domain/orders/entity/Orders.java, src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java, src/main/java/com/dangdangsalon/domain/orders/service/OrdersService.java, src/main/java/com/dangdangsalon/domain/payment/controller/PaymentController.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveRequestDto.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelRequestDto.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentDogProfileResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/entity/Payment.java, src/main/java/com/dangdangsalon/domain/payment/repository/PaymentRepository.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java, src/main/resources/db/migration/V6__ADD_orders_column.sql
> #37
> 주문 등록
> 결제 승인
> 결제 취소
> 내 정보에서 결제 내역 조회
> 
> 결제 맡은 프론트랑 많은 이야기 필요할 거 같아요...ㅎ
> 테이블 변경이 있는데 혼자 테스트할 때는 V5에 추가했는데 아직 커밋은 안 했습니다
> 정확성을 위해 더 고민중인데 일단 pr올렸고 어떤 점을 더 고려하면 좋을 지 이야기 해주시면 좋을 것 같아요!!
=> Feat: 주문 등록, 결제 승인, 결제 취소, 내 정보 결제 내역 조회 기능 구현

src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java, src/test/java/com/dangdangsalon/domain/estimate/request/api/EstimateRequestApiTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentGetServiceTest.java
> #40 
> 결제 내역 조회 미용사 이름 및 사진 추가
> 테스트 코드 수정
> 견적 요청 삭제(미용사) 로직 수정
> 
>
=> Refactor: 결제 내역 조회 미용사 이름 및 사진 추가

src/main/java/com/dangdangsalon/domain/mypage/dto/res/CommonProfileResponseDto.java, src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageCommonControllerTest.java
> #34 
> CommonProfileResponseDto에 name 컬럼 추가
>
=> Refactor: name 컬럼 추가

src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java, src/main/java/com/dangdangsalon/domain/region/repository/DistrictRepository.java, src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertServiceTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java
> #28
> 견적 요청 등록에 1대1 요청 등록 로직 추가
> 변경으로 인한 테스트 코드 작성
> 
>
=> Refactor: 견적 요청 등록에 1대1 요청 등록 로직 추가

src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageDogProfileController.java, src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java, src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageDogProfileControllerTest.java
> #34 
> 마이페이지 사용자 조회 api url 변경 (dogproflie -> userproflie)
>
=> Chore: 마이페이지 사용자 조회 api url 변경

src/main/java/com/dangdangsalon/config/CustomPrincipalArgumentResolver.java, src/main/java/com/dangdangsalon/config/SecurityConfig.java, src/main/java/com/dangdangsalon/config/StompConfig.java, src/main/java/com/dangdangsalon/config/WebSocketConfig.java, src/main/java/com/dangdangsalon/domain/auth/dto/CustomOAuth2User.java, src/main/java/com/dangdangsalon/domain/chat/controller/ChatController.java, src/main/java/com/dangdangsalon/domain/chat/dto/ChatMessageDto.java, src/main/java/com/dangdangsalon/domain/chat/handler/ChatSocketHandler.java, src/main/java/com/dangdangsalon/domain/chat/service/ChatService.java, src/main/java/com/dangdangsalon/domain/chat/util/ChatRedisUtil.java, src/main/java/com/dangdangsalon/filter/JwtAuthInterceptor.java, src/main/java/com/dangdangsalon/filter/WebSocketHandshakeInterceptor.java, src/main/resources/templates/chatsocket.html
=> Refactor: WebSocket -> STOMP 프로토콜 전환

src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java, src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateUpdateRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java, src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestResponseDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateUpdateService.java
> #28 
> 견적서 수정 기능 추가했습니다
> 견적서 거절하기 추가했습니다
> 
>
=> Refactor: 견적서 수정(미용사), 견적서 거절하기(사용자) 추가

src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateWriteRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java, src/test/java/com/dangdangsalon/domain/estimate/api/EstimateApiTest.java, src/test/java/com/dangdangsalon/domain/estimate/controller/EstimateControllerTest.java
> #37
> 견적서 보내기(미용사) 예약 날짜 저장 로직 변경, 결제 내역 조회 예약일 추가
> 
>
=> Refactor: 견적서 보내기(미용사) 예약 날짜 저장 로직 변경, 결제 내역 조회 예약일 추가

src/main/java/com/dangdangsalon/domain/chat/service/ChatRoomService.java, src/main/java/com/dangdangsalon/domain/contest/controller/ContestController.java, src/main/java/com/dangdangsalon/domain/contest/dto/ContestPaymentDto.java, src/main/java/com/dangdangsalon/domain/contest/dto/ContestPaymentRequestDto.java, src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateUpdateService.java, src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java, src/test/java/com/dangdangsalon/domain/contest/api/ContestApiTest.java, src/test/java/com/dangdangsalon/domain/contest/controller/ContestControllerTest.java, src/test/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepositoryTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentGetServiceTest.java
> ex) #72 
> 콘테스트 결제내역 조회, 견적서 수정 시 수정 견적서 채팅으로 보내기 및 테스트 코드 작성
>
=> Feature: 콘테스트 결제내역 조회, 견적서 수정 시 수정 견적서 채팅으로 보내기 및 테스트 코드 작성

src/main/java/com/dangdangsalon/domain/contest/service/ContestPostService.java, src/main/java/com/dangdangsalon/domain/contest/service/ContestTopicNotificationService.java, src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java, src/test/java/com/dangdangsalon/domain/contest/service/ContestPostServiceTest.java, src/test/java/com/dangdangsalon/domain/contest/service/ContestTopicNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/estimate/controller/EstimateControllerTest.java, src/test/java/com/dangdangsalon/domain/estimate/service/EstimateUpdateServiceTest.java
> #57 
> 구독 테스트 코드 작성 및 테스트 코드 수정
>
=> Test: 구독 테스트 코드 작성 및 테스트 코드 수정

src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java, src/main/java/com/dangdangsalon/domain/groomerprofile/review/dto/ReviewUserResponseDto.java, src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerController.java, src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerMainResponseDto.java, src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerRecommendResponseDto.java, src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java, src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java, src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerControllerTest.java, src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
> #34 
> 지역 추천 미용사, 전국 인기 미용사 기능 구현
> 
>
=> Feat: 지역 추천 미용사, 전국 인기 미용사 기능 구현

src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerProfileDetailsResponseDto.java, src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
> #34 
> Chore: 미용사 프로필 필수 등록 후 null 처리
>
=> Chore: 미용사 프로필 필수 등록 후 null 처리

src/main/java/com/dangdangsalon/domain/auth/dto/CheckLoginDto.java, src/main/java/com/dangdangsalon/domain/auth/service/AuthService.java, src/main/java/com/dangdangsalon/domain/auth/service/CustomOAuth2UserService.java
> #44
> checkLogin 에 알림 상태 값 추가
>
=> Refactor: checkLogin 에 알림 상태 값 추가

src/main/java/com/dangdangsalon/domain/notification/service/NotificationEmailService.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationScheduler.java, src/main/resources/templates/email.html, src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
=> Refactor: 이메일 알림 템플릿 적용

src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java
=> Refactor: 푸시 알림 로직 리팩토링

src/main/java/com/dangdangsalon/domain/auth/service/AuthService.java
=> Refactor: AuthService 수정

src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationScheduler.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
> #28
> 결제 후 견적 요청 상태 PAID 로 변경
>
=> Refactor: 결제 후 견적 요청 상태 PAID 로 변경 및 fcm 토큰 로직 수정

src/main/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepository.java, src/test/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepositoryTest.java
=> Refactor: 레포지토리 수정

src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
> #44
> 알림 setNotification -> putData 변경
>
=> Refactor: 알림 setNotification -> putData 변경

src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
> #44
> 토픽 알림 setNotification -> putData 변경
>
=> Refactor: 토픽 알림 setNotification -> putData 변경

src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
> #44
> 토픽 알림 setNotification -> putData 변경
>
=> 토픽 알림 setNotification -> putData 변경

src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java, src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java, src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
=> Refactor: 견적, 견적 요청, 결제 알림 비동기 처리

src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java, src/main/java/com/dangdangsalon/chatgpt/dto/ChatGPTMessage.java, src/main/java/com/dangdangsalon/chatgpt/dto/ChoiceResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageDataResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/MessageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateGptRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java, src/main/java/com/dangdangsalon/config/ChatGptConfig.java, src/main/java/com/dangdangsalon/config/MailConfig.java
=> Feat: Gpt open ai 활용 강아지 미용 후 사진 생성

src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java, src/main/java/com/dangdangsalon/chatgpt/dto/ChatGPTMessage.java, src/main/java/com/dangdangsalon/chatgpt/dto/ChoiceResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageDataResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/ImageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/MessageResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateGptRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateRequestDto.java, src/main/java/com/dangdangsalon/chatgpt/dto/TranslateResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java, src/main/java/com/dangdangsalon/config/ChatGptConfig.java, src/main/java/com/dangdangsalon/config/MailConfig.java, src/test/java/com/dangdangsalon/chatgpt/api/ChatGptApiTest.java, src/test/java/com/dangdangsalon/chatgpt/controller/ChatGptControllerTest.java, src/test/java/com/dangdangsalon/chatgpt/service/ChatGptServiceTest.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationEmailServiceTest.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationServiceTest.java
> #89
> chat gpt ai 테스트 코드 작성
> 
>
=> Test: chat gpt ai 테스트 코드 작성

src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java, src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java, src/test/java/com/dangdangsalon/chatgpt/api/ChatGptApiTest.java, src/test/java/com/dangdangsalon/chatgpt/controller/ChatGptControllerTest.java, src/test/java/com/dangdangsalon/chatgpt/service/ChatGptServiceTest.java
> #80 
> ai 이미지 분석 결과 기능 추가
> 
>
=> Refactor: ai 이미지 분석 결과 기능 추가

src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
> ex) #34 
> 견적 요청 개수 가져올 때, PENDING -> COMPLETED 로 변경
>
=> Chore: 견적 요청 개수 가져올 때, PENDING -> COMPLETED 로 변경

src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
=> Refactor: 강아지별 가격 수정

src/main/java/com/dangdangsalon/config/RedisConfig.java, src/main/java/com/dangdangsalon/domain/coupon/controller/CouponEventController.java, src/main/java/com/dangdangsalon/domain/coupon/dto/QueueStatusResponse.java, src/main/java/com/dangdangsalon/domain/coupon/listener/CouponEventListener.java, src/main/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepository.java, src/main/java/com/dangdangsalon/domain/coupon/repository/CouponRepository.java, src/main/java/com/dangdangsalon/domain/coupon/repository/ZSetRedisRepository.java, src/main/java/com/dangdangsalon/domain/coupon/service/CouponEventInitService.java, src/main/java/com/dangdangsalon/domain/coupon/service/CouponEventManageService.java, src/main/java/com/dangdangsalon/domain/coupon/service/CouponQueueService.java, src/main/java/com/dangdangsalon/domain/coupon/service/EventSetupRunner.java, src/main/java/com/dangdangsalon/domain/coupon/sse/SseEmitterRegistry.java, src/main/resources/static/coupon6.html
=> Feat: 쿠폰 발급 기능 1차 구현

build.gradle, src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
> #37 
> 결제 승인, 취소 에러 메시지 추가
>
=> Refactor: 결제 승인, 취소 에러 메시지 추가 및 재시도 로직 추가

src/main/java/com/dangdangsalon/domain/estimate/entity/EstimateStatus.java, src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java, src/main/resources/db/migration/V10__update_constraints.sql, src/main/resources/db/migration/V1__initial_schema.sql, src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
> #28
> 견적 상태 값 추가 및 회원 탈퇴 외래키로 인한 V1, V10 수정
> 결제 내역 조회 시 응답에 견적서 상태 값 추가
>
=> 견적 상태 값 추가 및 회원 탈퇴 외래키로 인한 V1, V10 수정

src/main/java/com/dangdangsalon/chatgpt/DogCelebrityMapping.java, src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
> #80
> DogCelebrityMapping 수정
>
=> Refactor: DogCelebrityMapping 수정

src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java, src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
> #80
> 이미지 분석 시 바로 한글 응답 오도록 수정
>
=> Refactor: 이미지 분석 시 바로 한글 응답 오도록 수정

src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
> #37
> 결제 내역 조회 응답 paymentKey 추가
>
=> Refactor: 결제 내역 조회 응답 paymentKey 추가

src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/scheduler/EstimateRequestStatusUpdateScheduler.java, src/main/java/com/dangdangsalon/domain/estimate/request/scheduler/GroomerEstimateRequestCleanupScheduler.java, src/main/java/com/dangdangsalon/domain/groomerprofile/request/repository/GroomerEstimateRequestRepository.java
> #28
> 예약 날짜 지나면 미용사에게 온 견적 요청 삭제
> 예약 날짜 지나면 사용자 견적 요청 상태 CANCEL 로 변경
>
=> 견젹 요청 삭제 및 상태 변경 스케줄러 추가

src/test/java/com/dangdangsalon/domain/coupon/api/CouponApiTest.java, src/test/java/com/dangdangsalon/domain/coupon/controller/CouponControllerTest.java, src/test/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepositoryTest.java, src/test/java/com/dangdangsalon/domain/coupon/service/CouponIssueServiceTest.java, src/test/java/com/dangdangsalon/domain/coupon/service/CouponSchedulerTest.java, src/test/java/com/dangdangsalon/domain/coupon/service/CouponServiceTest.java, src/test/java/com/dangdangsalon/domain/coupon/service/RedisMessageSubscriberTest.java
=> Test: 쿠폰 테스트 코드 작성

src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java, src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
=> Refactor: 결제 승인 취소 서비스 분리

src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java, src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerRecommendResponseDto.java, src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
> #34 
> 미용사 추천 정보 수정 및 프로필 전체 공개 페이지 설정
>
=> Refactor: 미용사 추천 정보 수정 및 프로필 전체 공개 페이지 설정

src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
=> Chore: 에러 메시지 수정

src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
=> fix: 테스트 코드 롤백

src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
> ex) #이슈번호, #이슈번호
Refactor: 이메일 알림 테스트
>
=> Refactor: 이메일 알림 테스트

src/main/java/com/dangdangsalon/domain/contest/service/ContestPostLikeService.java, src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java, src/main/java/com/dangdangsalon/domain/payment/repository/PaymentRepository.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java, src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
=> Refactor: 이메일 알림 로직 수정

src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java, src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
=> Refactor: 내 견적 요청 조회 로직 수정

src/main/java/com/dangdangsalon/domain/mypage/service/MyPageDogProfileService.java, src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java, src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java, src/main/java/com/dangdangsalon/domain/user/entity/User.java, src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
> #34 
> 결제 내역 조회 수정( 유저는 OrderStatus가 PENDING 아닐 때, 미용사는 OrderStatus가 Accepted ) 및 유저 cascade 조건 변경
>
=> Refactor: 결제 내역 조회 수정 및 유저 cascade 조건 변경

src/main/java/com/dangdangsalon/domain/notification/controller/NotificationController.java, src/main/java/com/dangdangsalon/domain/notification/entity/Topic.java, src/main/java/com/dangdangsalon/domain/notification/repository/TopicRepository.java, src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java, src/main/resources/db/migration/V12__alter_table_topic.sql, src/test/java/com/dangdangsalon/domain/notification/api/NotificationApiTest.java, src/test/java/com/dangdangsalon/domain/notification/controller/NotificationControllerTest.java, src/test/java/com/dangdangsalon/domain/notification/service/NotificationTopicServiceTest.java
=> 구독 알림 기능 리팩토링

src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java, src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java
=> Refactor: 결제 알림 미용사한테 가도록 수정

src/main/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationService.java, src/test/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationServiceTest.java
=> 이벤트 알림 조회 시간 수정

src/main/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationService.java, src/main/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepository.java, src/test/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationServiceTest.java
=> Refactor: 이벤트 알림 미용사 제외

src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java, src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerController.java, src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java, src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java, src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerControllerTest.java, src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
> #34 , #47 
> 미용사 닉네임 중복 확인
>
=> Refactor: 미용사 닉네임 중복 확인

src/main/java/com/dangdangsalon/config/SchedulerConfig.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> Fix: 스케줄러 버그 수정
